# Generated by Django 5.1.5 on 2025-01-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('description',)},
        ),
    ]
