# Generated by Django 5.1.5 on 2025-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_transaction_id_alter_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
